name: Feature Branch

on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Package
        run: mvn -B -T 1C -B clean package -DskipTests=true
      - name: Checkstyle
        run: mvn -B checkstyle:check options=-Dmaven.test.skip=true
      - name: Unit tests
        run: mvn -B test