name: Feature Branch

on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-
      - name: Compile & Package
        run: mvn -B -T 1C clean package -DskipTests=true
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-jar
          path: target/*.jar

  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-
      - name: Download Compiled Artifacts
        uses: actions/download-artifact@v4
        with:
          name: compiled-jar
          path: target
      - name: Run Checkstyle
        run: mvn -B checkstyle:check -Dmaven.test.skip=true

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: checkstyle
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-
      - name: Download Compiled Artifacts
        uses: actions/download-artifact@v4
        with:
          name: compiled-jar
          path: target
      - name: Run Unit Tests
        run: mvn -B test
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.1.0
        with:
         args: >
           -Dsonar.organization=room-elephant
           -Dsonar.projectKey=Room-Elephant_elephub
           -Dsonar.java.binaries=target
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}